### PR TITLE
add special case for bytes()

### PR DESCRIPTION
**Pull request by thebabush**
Hi,

I noticed in the code that there's a special case for `str()` but not for `bytes()` so I added it and made a simple test (it tests that special cases are added to both add and __contains__).

Let me know what you think.

babush

### CODE REVIEW

**Comment by prashnts** [comment]
Looks good to me, although I made a conflict in tests! X)

Will have a look at this next.

**Review by prashnts — APPROVED** [review]

**Comment by thebabush** [comment]
:+1:

**Comment by pianist-coder** [comment]
Not working.

**Comment by prashnts** [comment]
> Not working.

Please could you be a bit more precise? I guess a "what isn't working", "in which context", and "in which environment" would help.

**Pull request merged**
